CREATE TABLE `person` (
  `id_person` int(11) NOT NULL,
  `id_address` int(11) NOT NULL,
  `name` varchar(15) NOT NULL,
  `last_name` varchar(15) NOT NULL,
  `birthdate` date DEFAULT NULL,
  `gender` char(1) DEFAULT NULL,
  `email` varchar(35) DEFAULT NULL,
  `phone` varchar(10) DEFAULT NULL,
  `user` varchar(8) DEFAULT NULL,
  `password` varchar(8) DEFAULT NULL,
  `status` tinyint(1) DEFAULT NULL,
  `role` varchar(8) DEFAULT NULL,
  PRIMARY KEY (`id_person`),